### ISSUE TITLE
Redirect to veracity.com/auth/logout on sign-out

### ISSUE THREAD

**Issue by objorke** [veracity/generator-veracity#3]
Redirect to https://veracity.com/auth/logout for the "official" Veracity logout process

https://github.com/veracity/generator-veracity/blob/master/generators/netcore-webapp/templates/appnetcore/Controllers/AccountController.cs#L36

**Comment by rudfoss** [comment]
@mingderekwang Can you check this out?

**Comment by rudfoss** [comment]
This has been resolved for the SPA
