### ISSUE TITLE
Don't use template variables in appnetcore solution name, project name and namespaces

### ISSUE THREAD

**Issue by objorke** [veracity/generator-veracity#5]
It would be easier to maintain the solution and projects if it didn't use `<%= projectName %>`

- Simply use "appnetcore" everywhere, let the user rename himself after the generator has completed
- Consider not including the solution file (it is more work to rename a project in a solution)
- The namespace of `Program.cs` and `Startup.cs` is not consistent with the other cs files

**Comment by mingderekwang** [comment]
For the first two points, we will put this into developer.veracity.com when developer create the application, but in generator, we will still use template to reduce the work for developer. 
Third issue has been fixed.
