### ISSUE TITLE
Node template: remove files in cert folder

### ISSUE THREAD

**Issue by objorke** [veracity/generator-veracity#8]
Remove files in
https://github.com/veracity/generator-veracity/tree/master/generators/node-webapp-demo/templates/cert
as they create an issue during credential scanning.

The certificate should be generated by the user as described in 
https://github.com/veracity/generator-veracity/blob/master/generators/node-webapp-demo/templates/server.js#L22

**Comment by rudfoss** [comment]
I'm not sure we want to do this as it dramatically reduces the overhead for new developers. Will check the code. In any case the certs are invalid and this code is only intended as a sample.

**Comment by objorke** [comment]
These repositories should be scanned for credentials/secrets. Certificates are classified as findings. We can add exceptions by hash code or path.

**Comment by rudfoss** [comment]
Certs are now automatically generated once the application starts. No need for hard-coded certs anymore.
